steps:
    - name: node:12.11.0
      entrypoint: npm
      args: ['install']
      dir: 'web'
    - name: node:12.11.0
      entrypoint: npm
      args: ['run', 'create-env']
      dir: 'web'
      env:
          - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
          - 'GOOGLE_SPREADSHEET_ID=${_GOOGLE_SPREADSHEET_ID}'
          - 'GOOGLE_SPREADSHEET_KEY=${_GOOGLE_SPREADSHEET_KEY}'
          - 'SPOTIFY_CLIENTD_APP=${_SPOTIFY_CLIENTD_APP}'
          - 'SPOTIFY_SUMMER_TRACKS_ENDPOINT=${_SPOTIFY_SUMMER_TRACKS_ENDPOINT}'
          - 'SPOTIFY_SUMMER_CONFIRMATION_ENDPOINT=${_SPOTIFY_SUMMER_CONFIRMATION_ENDPOINT}'
          - 'SPOTIFY_APP_SCOPE=${_SPOTIFY_APP_SCOPE}'
          - 'SPOTIFY_API_BASE=${_SPOTIFY_API_BASE}'
          - 'SPOTIFY_APP_SCOPE=${_SPOTIFY_APP_SCOPE}'
          - 'SPOTIFY_API_MAX_RETRIES=${_SPOTIFY_API_MAX_RETRIES}'
    - name: node:12.11.0
      entrypoint: npm
      args: ['run', 'prod']
      dir: 'web'
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['app', 'deploy', '--no-promote', '--version=$BRANCH_NAME']
      dir: 'web'
timeout: '1600s'
